name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on master/main push
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # ADD THESE TWO LINES TO SAVE THE FILE
          filename: github-metrics.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: VaibhavKumar2005
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
